spring:
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: bank-information-service
  cloud:
    config:
      uri: http://localhost:8888
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

