server:
  port: 9411

spring:
  main:
    allow-bean-definition-overriding: true

management:
  metrics:
    web:
      server:
        auto-time-requests: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/